defaultNamespace: ns-047
labels:
  app: busybox-suite
  instance: "047"

# Resources to be deployed
resourceLabels:
  heritage: fleet

---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-047
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: ns-047
spec:
  containers:
  - name: busybox
    image: busybox
    args: [/bin/sh, -c, "sleep 3600"]
