defaultNamespace: ns-059
labels:
  app: busybox-suite
  instance: "059"

# Resources to be deployed
resourceLabels:
  heritage: fleet

---
apiVersion: v1
kind: Namespace
metadata:
  name: ns-059
---
apiVersion: v1
kind: Pod
metadata:
  name: busybox-pod
  namespace: ns-059
spec:
  containers:
  - name: busybox
    image: busybox
    args: [/bin/sh, -c, "sleep 3600"]
